services:
  db: 
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data: